### ISSUE TITLE
서버에 연결하는 방법을 잘 모르겠습니다. 

### ISSUE THREAD

**Issue by moonchildz** [DatathonInfo/L.C.A.I.2021#2]
![image](https://user-images.githubusercontent.com/66664844/145764600-dc338d2d-53e0-4bb4-a28a-063c04817ed3.png)

putty 를 이용하여 서버에 연결까지는 어떻게 된 것 같은데 이 다음을 어떻게 해야할 지 잘 모르겠습니다. 

이 다음에 jupyter notebook 을 제 컴퓨터에서 실행하면 되는 건가요 ? putty 에서 실행했을 때는 제 서버에 연결이 되지 않았습니다.

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

제공해드린 서버에서 jupyter notebook은 기본적으로 실행되어 있습니다.
인터넷 브라우저에서 `http://[제공해드린 Host IP]:8888` 로 접속하실 수 있습니다.

감사합니다.
L.C.A.I.2021 운영팀 드림

**Comment by kdha0727** [comment]
ssh 연결할때 -L8888:localhost:8888로 tunneling해보시면 될 거 같습니다

**Comment by moonchildz** [comment]
연결 확인했습니다. 감사합니다.
